#!/usr/bin/env python3
"""Inject per-vertical NICHE prompts into the Suggest Replies (панель «Вместе») workflow.

Sources:  Tools/n8n/prompts/panel/<vertical_id>.md  (NOT composed with _core.md -- that
          tail is Авто-only: Chat Memory, the Vector Store *tool*, and reply-format rules
          the panel's own system prompt already covers and partly contradicts)
Targets:  no args  -> Tools/n8n/workflows/9PTyYcelRQI7bGDb-Suggest_Replies.json
          paths    -> transform those JSON files in place (e.g. live-fetched copies)
Flags:    --check  -> don't write; exit 2 if any file would change, 0 if all up to date

The first run MIGRATES the hand-written one-line HINTS map into the generated
PANEL_PROMPTS block; later runs only regenerate the map between the markers.
Idempotent. Fails loudly on unexpected workflow shape.

Companion gate: Tools/n8n/verify-panel-prompts.js asserts the COMPOSED systemPrompt
actually carries each niche block -- run it after this script.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PANEL_DIR = ROOT / "prompts" / "panel"
WORKFLOWS_DIR = ROOT / "workflows"

VERTICALS = ["auto_parts", "wholesale", "flowers", "kaspi_seller", "education", "phone_repair"]

DEFAULT_TARGETS = [WORKFLOWS_DIR / "9PTyYcelRQI7bGDb-Suggest_Replies.json"]

NODE_NAME = "Assemble"
BEGIN = ("// PANEL-PROMPTS-BEGIN (generated by Tools/n8n/inject-panel-prompts.py"
         " -- edit Tools/n8n/prompts/panel/*.md instead)")
END = "// PANEL-PROMPTS-END"

# The push site is marker-wrapped too, so the header wording below can be reworded without
# stranding the injector: regeneration keys on the markers, never on the header text. (It
# was reworded once already -- see NEW_PUSH.)
PUSH_BEGIN = "// PANEL-NICHE-PUSH-BEGIN"
PUSH_END = "// PANEL-NICHE-PUSH-END"

# The hand-written map this script replaces, verbatim as it appears after json.load.
OLD_MAP = (
    "const HINTS = {\n"
    "  auto_parts: 'перед точной ценой выясняй марку/модель/год/объём или VIN;"
    " предлагай аналоги дешевле оригинала.',\n"
    "  wholesale: 'цена зависит от объёма партии — уточняй количество;"
    " предлагай отправить прайс.',\n"
    "  flowers: 'уточняй дату, повод и бюджет; предлагай фото готовых букетов;"
    " напоминай про доставку.',\n"
    "  kaspi_seller: 'рассрочка и оплата — всегда через оформление в магазине на Kaspi"
    " (рассрочка Kaspi у продавца ЕСТЬ — не отрицай её наличие);"
    " оплату в переписке не принимаем.',\n"
    "  education: 'уточняй возраст и уровень; предлагай пробное занятие;"
    " веди к записи в группу/расписанию.',\n"
    "  phone_repair: 'уточняй модель устройства и симптом; предлагай бесплатную диагностику;"
    " называй срок и гарантию.'\n"
    "};\n"
    "const hint = HINTS[p.businessTypeId] || '';"
)

OLD_PUSH = "if (hint) { L.push(''); L.push('НИША: ' + hint); }"

# Subordination is SCOPED, and the scoping is load-bearing. v1 said "формат, длина и
# грануляция из правил выше ГЛАВНЕЕ", which the model over-read: it demoted the niche's
# CONTENT rules too, so for `колодки передние сколько стоят?` card 1 quoted the catalog
# price instead of asking марка/модель/год (2026-08-11 A/B probe, P_autoparts_intake).
# The niche must outrank the DEFAULT RANKING HEURISTIC -- which otherwise reasons "the price
# is in ДАННЫЕ, so «Ответ» is confident enough to lead" -- while still yielding on output
# shape, where niche prose would blow the <=220-char cap and the schema.
NEW_PUSH = (
    "if (niche) { L.push(''); L.push('НИША (правила твоей отрасли: они определяют, что нужно"
    " уточнить ПЕРЕД ответом, чего нельзя утверждать и каким ходом отвечать — в этом они"
    " ГЛАВНЕЕ общих правил ранжирования. Формат, длина и число карточек — по правилам выше.):');"
    " L.push(niche); }"
)


def load_panel_prompts() -> dict:
    prompts = {}
    for vid in VERTICALS:
        path = PANEL_DIR / f"{vid}.md"
        if not path.exists():
            raise SystemExit(f"ERROR: missing panel prompt {path}")
        body = path.read_text(encoding="utf-8").strip()
        if not body:
            raise SystemExit(f"ERROR: empty panel prompt {path}")
        prompts[vid] = body
    return prompts


def build_map_block(prompts: dict) -> str:
    return (
        f"{BEGIN}\n"
        f"const PANEL_PROMPTS = {json.dumps(prompts, ensure_ascii=False, indent=2)};\n"
        f"{END}\n"
        "const niche = PANEL_PROMPTS[p.businessTypeId] || '';"
    )


def node_by_name(wf: dict, name: str):
    for n in wf["nodes"]:
        if n["name"] == name:
            return n
    return None


def patch_assemble(wf: dict, map_block: str) -> None:
    node = node_by_name(wf, NODE_NAME)
    if node is None:
        raise SystemExit(f"ERROR: '{NODE_NAME}' node not found; refusing to guess")
    code = node["parameters"]["jsCode"]

    # 1. The map: regenerate between markers if already migrated, else migrate from HINTS.
    if BEGIN in code:
        if END not in code:
            raise SystemExit(f"ERROR: {BEGIN!r} present but {END!r} missing; refusing to guess")
        start = code.index(BEGIN)
        tail = code.index(END) + len(END)
        # The generated block owns the `const niche = ...` line that follows the END marker.
        nl = code.index("\n", tail)
        decl_end = code.index("\n", nl + 1)
        code = code[:start] + map_block + code[decl_end:]
    elif OLD_MAP in code:
        code = code.replace(OLD_MAP, map_block)
    else:
        raise SystemExit("ERROR: neither the PANEL-PROMPTS markers nor the original HINTS "
                         "map found in Assemble; refusing to guess")

    # 2. The push site: regenerate between markers if migrated, else migrate from the
    #    original one-line HINTS push.
    wrapped = f"{PUSH_BEGIN}\n{NEW_PUSH}\n{PUSH_END}"
    if PUSH_BEGIN in code:
        if PUSH_END not in code:
            raise SystemExit(f"ERROR: {PUSH_BEGIN!r} present but {PUSH_END!r} missing; "
                             "refusing to guess")
        start = code.index(PUSH_BEGIN)
        end = code.index(PUSH_END) + len(PUSH_END)
        code = code[:start] + wrapped + code[end:]
    elif OLD_PUSH in code:
        code = code.replace(OLD_PUSH, wrapped)
    else:
        raise SystemExit("ERROR: neither the PANEL-NICHE-PUSH markers nor the original НИША "
                         f"push found in Assemble; refusing to guess. Fragment:\n{OLD_PUSH}")

    node["parameters"]["jsCode"] = code


def main() -> None:
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    targets = [Path(a) for a in args] if args else DEFAULT_TARGETS
    map_block = build_map_block(load_panel_prompts())
    changed = []
    for path in targets:
        original = path.read_text(encoding="utf-8")
        wf = json.loads(original)
        patch_assemble(wf, map_block)
        result = json.dumps(wf, ensure_ascii=False, indent=2) + "\n"
        if result != original:
            changed.append(path)
            if not check:
                path.write_text(result, encoding="utf-8")
        print(f"{path.name}: {'CHANGED' if result != original else 'up-to-date'}")
    if check and changed:
        sys.exit(2)


if __name__ == "__main__":
    main()
