#!/usr/bin/env python3
"""Inject vertical main prompts into the bot Create/Edit n8n workflows.

Sources:  Tools/n8n/prompts/_core.md + <vertical_id>.md  (composed as vertical + "\n\n" + core)
Targets:  no args  -> the 4 canonical workflow JSONs in Tools/n8n/workflows/
          paths    -> transform those JSON files in place (e.g. live-fetched copies)
Flags:    --check  -> don't write; exit 2 if any file would change, 0 if all up to date

Idempotent. Fails loudly on unexpected workflow shape.
"""
import json
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PROMPTS_DIR = ROOT / "prompts"
WORKFLOWS_DIR = ROOT / "workflows"

VERTICALS = ["auto_parts", "wholesale", "flowers", "kaspi_seller", "education", "phone_repair"]

DEFAULT_TARGETS = [
    WORKFLOWS_DIR / "XuvOp7TxOImOAmlj-CreateWhatsappWorkflow.json",
    WORKFLOWS_DIR / "Uz6HBBUpAiUqVysB-CreateTelegramWorkflow.json",
    WORKFLOWS_DIR / "3qax5J9u2qsT9Vao-Edit_Whatsapp_Workflow.json",
    WORKFLOWS_DIR / "TwWPW3gIyjZS3foR-Edit_Telegram_Workflow.json",
]

NODE_NAME = "Vertical Prompt"
SYSMSG_FIELD = "nodes[5].parameters.options.systemMessage"

# Exact expression fragments as they appear AFTER json.load (i.e. real chars; "\\n" below is
# backslash+n inside the n8n expression source, not a newline).
CREATE_OLD = "{{ $json.nodes[5].parameters.options.systemMessage.slice(1) }}"
CREATE_NEW = ("{{ $('Vertical Prompt').first().json.verticalPrompt"
              " || $json.nodes[5].parameters.options.systemMessage.slice(1) }}")

EDIT_OLD_HEAD = ('{{ $json.nodes[5].parameters.options.systemMessage.slice(0, '
                 '$json.nodes[5].parameters.options.systemMessage.indexOf("\\n" + '
                 '"Additional Instructions: ")); }}')
EDIT_NEW_HEAD = ("{{ $('Vertical Prompt').first().json.verticalPrompt ? "
                 '"Business Type: " + $(\'Unity Webhook\').first().json.body.BusinessType + '
                 '"\\n\\n" + $(\'Vertical Prompt\').first().json.verticalPrompt + "\\n" : '
                 '$json.nodes[5].parameters.options.systemMessage.slice(0, '
                 '$json.nodes[5].parameters.options.systemMessage.indexOf("\\n" + '
                 '"Additional Instructions: ")) }}')


def load_prompts() -> dict:
    core = (PROMPTS_DIR / "_core.md").read_text(encoding="utf-8").strip()
    prompts = {}
    for vid in VERTICALS:
        body = (PROMPTS_DIR / f"{vid}.md").read_text(encoding="utf-8").strip()
        prompts[vid] = body + "\n\n" + core
    return prompts


def build_jscode(prompts: dict) -> str:
    return (
        "// PROMPTS-BEGIN (generated by Tools/n8n/inject-prompts.py -- edit Tools/n8n/prompts/*.md instead)\n"
        f"const PROMPTS = {json.dumps(prompts, ensure_ascii=False, indent=2)};\n"
        "// PROMPTS-END\n"
        "const id = ($('Unity Webhook').first().json.body || {}).BusinessTypeId || \"\";\n"
        "const verticalPrompt = PROMPTS[id] || \"\";\n"
        "return [{ json: { ...$input.first().json, verticalPrompt }, pairedItem: { item: 0 } }];\n"
    )


def node_by_name(wf: dict, name: str):
    for n in wf["nodes"]:
        if n["name"] == name:
            return n
    return None


def detect_kind(wf: dict) -> str:
    names = {n["name"] for n in wf["nodes"]}
    if "Get Sample Workflow" in names:
        return "create"
    if "Get Workflow" in names and "Set Bussiness Type" in names:
        return "edit"
    raise SystemExit(f"ERROR: unrecognized workflow shape (nodes: {sorted(names)})")


def ensure_vertical_node(wf: dict, kind: str, jscode: str) -> None:
    prev_name, next_name = (
        ("Unity Webhook", "Get Sample Workflow") if kind == "create"
        else ("Get Workflow", "Set Bussiness Type")
    )
    node = node_by_name(wf, NODE_NAME)
    if node is None:
        prev = node_by_name(wf, prev_name)
        nxt = node_by_name(wf, next_name)
        if prev is None or nxt is None:
            raise SystemExit(f"ERROR: anchor nodes missing ({prev_name}/{next_name})")
        pos = [(prev["position"][0] + nxt["position"][0]) // 2,
               prev["position"][1] - 176]
        node = {
            "parameters": {"jsCode": jscode},
            "type": "n8n-nodes-base.code",
            "typeVersion": 2,
            "position": pos,
            "id": str(uuid.uuid4()),
            "name": NODE_NAME,
        }
        wf["nodes"].append(node)
        # rewire: prev -> Vertical Prompt -> next, touching only the existing
        # prev -> next main[0] link; other links, outputs and error connections
        # on the anchor node are preserved.
        main = wf["connections"].setdefault(prev_name, {}).setdefault("main", [])
        if not main:
            main.append([])
        link = next((l for l in main[0] if l.get("node") == next_name), None)
        if link is None:
            raise SystemExit(f"ERROR: expected connection {prev_name} -> {next_name} "
                             f"not found; refusing to rewire")
        next_input_index = link.get("index", 0)
        link["node"] = NODE_NAME
        link["index"] = 0
        wf["connections"][NODE_NAME] = {
            "main": [[{"node": next_name, "type": "main", "index": next_input_index}]]
        }
    else:
        node["parameters"]["jsCode"] = jscode


def patch_set_fields(wf: dict, kind: str) -> None:
    sf = node_by_name(wf, "Set Fields")
    if sf is None:
        raise SystemExit("ERROR: 'Set Fields' node not found")
    for a in sf["parameters"]["assignments"]["assignments"]:
        if a["name"] != SYSMSG_FIELD:
            continue
        old, new = (CREATE_OLD, CREATE_NEW) if kind == "create" else (EDIT_OLD_HEAD, EDIT_NEW_HEAD)
        if new in a["value"]:
            return  # already patched
        if old not in a["value"]:
            raise SystemExit(f"ERROR: expected expression fragment not found in Set Fields "
                             f"({kind}); refusing to guess. Fragment:\n{old}")
        a["value"] = a["value"].replace(old, new)
        return
    raise SystemExit(f"ERROR: Set Fields has no assignment for {SYSMSG_FIELD}")


def main() -> None:
    args = [a for a in sys.argv[1:] if a != "--check"]
    check = "--check" in sys.argv[1:]
    targets = [Path(a) for a in args] if args else DEFAULT_TARGETS
    prompts = load_prompts()
    jscode = build_jscode(prompts)
    changed = []
    for path in targets:
        original = path.read_text(encoding="utf-8")
        wf = json.loads(original)
        kind = detect_kind(wf)
        ensure_vertical_node(wf, kind, jscode)
        patch_set_fields(wf, kind)
        result = json.dumps(wf, ensure_ascii=False, indent=2) + "\n"
        if result != original:
            changed.append(path)
            if not check:
                path.write_text(result, encoding="utf-8")
        print(f"{path.name}: kind={kind} {'CHANGED' if result != original else 'up-to-date'}")
    if check and changed:
        sys.exit(2)


if __name__ == "__main__":
    main()
