using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Composes a chat row's last-message preview in WhatsApp format:
///   [tick-sprite]? [media-emoji]? [text]
///
/// Tick sprites reference the ChatTicks TMP Sprite Asset (generated by
/// ChatTicksSpriteAssetBuilder). Media emoji are raw Unicode chars that
/// the caller must run through UnicodeEmojiConverter.ConvertRealEmojisToSprites
/// to become EmojiOne sprite tags.
///
/// Pure static + no state. Unknown Wappi values log once per session via the
/// dedup HashSets to surface API drift without flooding the console.
/// </summary>
public static class ChatPreviewFormatter
{
    // Must match the sprite character names in ChatTicks.asset (generated by
    // ChatTicksSpriteAssetBuilder). The asset is registered as a fallback of
    // TMP's default sprite asset by ChatTicksFallbackRegistrar at startup, so
    // bare <sprite name="X"> tags resolve through TMP's fallback chain.
    private const string TickSent = "tick_sent";
    private const string TickDouble = "tick_double";
    private const string TickDoubleBlue = "tick_double_blue";

    // One-time discovery log per unknown Wappi value.
    private static readonly HashSet<string> LoggedUnknownTypes = new();
    private static readonly HashSet<string> LoggedUnknownStatuses = new();

    public static string Format(string rawText, string type, string deliveryStatus, bool isMine)
    {
        var tick = isMine ? GetTickSprite(deliveryStatus) : null;
        var (emoji, label) = GetMediaInfo(type);
        var text = rawText ?? string.Empty;

        // When Wappi sends the body as the bare type keyword (e.g. "image" for
        // an image with no caption) or leaves it empty, substitute the
        // WhatsApp-style English label so the row reads "📷 Photo" rather
        // than "📷 image". Real captions and chat text are preserved as-is.
        //
        // UnicodeEmojiConverter prepends a zero-width space (U+200B) to its
        // output in ChatManager.ParseChatsJson, so the body looks like
        // "​image" rather than "image". Strip ZWS and surrounding
        // whitespace before comparing.
        if (label != null)
        {
            var stripped = text.Trim('​', ' ', '\t', '\n', '\r');
            if (stripped.Length == 0
                || string.Equals(stripped, type, System.StringComparison.OrdinalIgnoreCase)
                || string.Equals(stripped, label, System.StringComparison.OrdinalIgnoreCase))
            {
                text = label;
            }
        }

        if (tick == null && emoji == null) return text;

        var sb = new System.Text.StringBuilder(text.Length + 48);
        if (tick != null) { sb.Append(tick); sb.Append(' '); }
        if (emoji != null) { sb.Append(emoji); sb.Append(' '); }
        sb.Append(text);
        return sb.ToString();
    }

    private static string GetTickSprite(string status)
    {
        if (string.IsNullOrEmpty(status)) return null;
        switch (status.ToLowerInvariant())
        {
            // Bare <sprite name=...> resolves via TMP's hash-code search across
            // the current sprite asset → its fallback list → TMP_Settings'
            // defaultSpriteAsset → its fallback list. ChatTicksFallbackRegistrar
            // adds ChatTicks to the default sprite asset's fallback list at
            // runtime so this lookup finds tick_X glyphs without us having to
            // assign ChatTicks per-TMP-component.
            case "sent":      return $"<sprite name=\"{TickSent}\">";
            case "delivered": return $"<sprite name=\"{TickDouble}\">";
            case "read":      return $"<sprite name=\"{TickDoubleBlue}\">";
            default:
                if (LoggedUnknownStatuses.Add(status))
                    Debug.LogWarning($"[ChatPreviewFormatter] Unknown delivery status: '{status}'");
                return null;
        }
    }

    /// <summary>
    /// Returns the (emoji, label) for a Wappi message type. The label is the
    /// proper-cased name shown when Wappi's body is empty or duplicates the
    /// type keyword. Reaction returns (null, null) because Wappi pre-formats
    /// the full reaction sentence in `last_message_data` (e.g.
    /// "Отреагировал(-а) ☺ на '...'") — adding a prefix would clutter it.
    /// </summary>
    private static (string emoji, string label) GetMediaInfo(string type)
    {
        if (string.IsNullOrEmpty(type)) return (null, null);
        switch (type.ToLowerInvariant())
        {
            case "chat":
            case "text":     return (null, null);
            case "image":
            case "photo":    return ("📷", "Photo");
            case "video":    return ("📹", "Video");
            case "voice":
            case "ptt":      return ("🎤", "Voice");
            case "audio":    return ("🎵", "Audio");
            case "document": return ("📄", "Document");
            case "location": return ("📍", "Location");
            case "sticker":  return (null, "Sticker"); // EmojiOne lacks a clean sticker glyph.
            case "vcard":
            case "contact":  return ("👤", "Contact");
            case "reaction": return (null, null); // Wappi pre-formats the full sentence.
            default:
                if (LoggedUnknownTypes.Add(type))
                    Debug.LogWarning($"[ChatPreviewFormatter] Unknown message type: '{type}'");
                return (null, null);
        }
    }
}
