using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Composes a chat row's last-message preview in WhatsApp format:
///   [tick-sprite]? [media-emoji]? [text]
///
/// Tick sprites reference the ChatTicks TMP Sprite Asset (generated by
/// ChatTicksSpriteAssetBuilder). Media emoji are raw Unicode chars that
/// the caller must run through UnicodeEmojiConverter.ConvertRealEmojisToSprites
/// to become EmojiOne sprite tags.
///
/// Pure static + no state. Unknown Wappi values log once per session via the
/// dedup HashSets to surface API drift without flooding the console.
/// </summary>
public static class ChatPreviewFormatter
{
    // Must match the sprite character names in ChatTicks.asset (generated by
    // ChatTicksSpriteAssetBuilder).
    private const string TickAssetName = "ChatTicks";
    private const string TickSent = "tick_sent";
    private const string TickDouble = "tick_double";
    private const string TickDoubleBlue = "tick_double_blue";

    // One-time discovery log per unknown Wappi value.
    private static readonly HashSet<string> LoggedUnknownTypes = new();
    private static readonly HashSet<string> LoggedUnknownStatuses = new();

    public static string Format(string rawText, string type, string deliveryStatus, bool isMine)
    {
        var tick = isMine ? GetTickSprite(deliveryStatus) : null;
        var emoji = GetMediaEmoji(type);
        var text = rawText ?? string.Empty;

        if (tick == null && emoji == null) return text;

        var sb = new System.Text.StringBuilder(text.Length + 48);
        if (tick != null) { sb.Append(tick); sb.Append(' '); }
        if (emoji != null) { sb.Append(emoji); sb.Append(' '); }
        sb.Append(text);
        return sb.ToString();
    }

    private static string GetTickSprite(string status)
    {
        if (string.IsNullOrEmpty(status)) return null;
        switch (status.ToLowerInvariant())
        {
            case "sent":      return $"<sprite=\"{TickAssetName}\" name=\"{TickSent}\">";
            case "delivered": return $"<sprite=\"{TickAssetName}\" name=\"{TickDouble}\">";
            case "read":      return $"<sprite=\"{TickAssetName}\" name=\"{TickDoubleBlue}\">";
            default:
                if (LoggedUnknownStatuses.Add(status))
                    Debug.LogWarning($"[ChatPreviewFormatter] Unknown delivery status: '{status}'");
                return null;
        }
    }

    private static string GetMediaEmoji(string type)
    {
        if (string.IsNullOrEmpty(type)) return null;
        switch (type.ToLowerInvariant())
        {
            case "chat":
            case "text":     return null;
            case "image":
            case "photo":    return "📷";
            case "video":    return "📹";
            case "voice":
            case "ptt":      return "🎤";
            case "audio":    return "🎵";
            case "document": return "📄";
            case "location": return "📍";
            case "sticker":  return null; // EmojiOne lacks a clean sticker glyph.
            default:
                if (LoggedUnknownTypes.Add(type))
                    Debug.LogWarning($"[ChatPreviewFormatter] Unknown message type: '{type}'");
                return null;
        }
    }
}
